language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings

    - echo Build Framework
    - xcodebuild clean build -scheme 'QTEventBus' -configuration Debug | xcpretty -c

    - echo Build the Demo apps
    - xcodebuild build -scheme 'Demo' -configuration Debug -destination 'name=iPhone 6s' | xcpretty -c

    - echo Run the tests
    - xcodebuild clean -scheme 'Demo' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild test -scheme 'QTEventBus' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -configuration Debug | xcpretty -c